package de.felixlf.gradingscale2.entities

import app.cash.molecule.RecompositionMode
import app.cash.molecule.launchMolecule
import app.cash.turbine.TurbineTestContext
import app.cash.turbine.test
import de.felixlf.gradingscale2.entities.uimodel.UIModel
import de.felixlf.gradingscale2.entities.uimodel.UIModelWithEvents
import kotlinx.coroutines.test.TestScope

/**
 * Helper function which helps test UIModels with molecule.
 * We should not use the uiState, as that is automatically generated by a molecule using RecompositionMode.ContextClock, which is not
 * available in the TestScope, so an exception would be thrown.
 * For tests, it is easier using instead the Immediate mode.
 */
suspend fun <UIState, UICommand, UIEvent> TestScope.testMoleculeFlow(
    uiModelWithEvents: UIModelWithEvents<UIState, UICommand, UIEvent>,
    validate: suspend TurbineTestContext<UIState>.() -> Unit,
) = backgroundScope.launchMolecule(mode = RecompositionMode.Immediate, body = { uiModelWithEvents.produceUI() }).test(validate = validate)

suspend fun <UIState, UICommand> TestScope.testMoleculeFlow(
    uiModelWithEvents: UIModel<UIState, UICommand>,
    validate: suspend TurbineTestContext<UIState>.() -> Unit,
) = backgroundScope.launchMolecule(mode = RecompositionMode.Immediate, body = { uiModelWithEvents.produceUI() }).test(validate = validate)
